name: re3
base: core20
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Rebuild of GTA III new platforms.
description: |
    Rebuild of GTA III for new platforms.
grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

apps:
    re3:
        command: usr/bin/re3-launch
        command-chain: [bin/desktop-launch]
        environment: 
            PULSE_RUNTIME_PATH: /var/run/pulse
            PULSE_SYSTEM: 1
            #            GTA_III_RE_DIR: $SNAP_USER_COMMON/GTAIII 
        plugs:
            - opengl
            - audio-playback
parts:
    desktop-glib-only:
        source: snap/local
        source-subdir: glib-only
        source-type: local
        plugin: make
        build-packages:
            - libglib2.0-dev
        stage-packages:
            - libglib2.0-bin

    my-part:
        after :
            - desktop-glib-only 
        source-type: local
        source: .
        plugin: dump
        source-subdir: build
        override-build: |
            ./premake5Linux --with-librw gmake2
            make -C build config=release_linux-amd64-librw_gl3_glfw-oal
            mkdir -p $SNAPCRAFT_PART_INSTALL/usr/bin
            install -m 755 bin/linux-amd64-librw_gl3_glfw-oal/Release/re3 $SNAPCRAFT_PART_INSTALL/usr/bin
            install -m 755 snap/local/re3-launch $SNAPCRAFT_PART_INSTALL/usr/bin
        build-packages:
                - libglew-dev
                - libglfw3-dev
                - libmpg123-dev
                - libopenal-dev
                - libpulse-dev
                - libsndfile1-dev
        stage-packages:
                - libasound2
                - libflac8
                - libgl1 
                - libglew2.1
                - libglfw3
                - libglvnd0
                - libglx0
                - libmpg123-0
                - libogg0
                - libopenal1
                - libpulse0
                - libsndfile1
                - libsndio7.0
                - libvorbis0a
                - libvorbisenc2
                - libx11-6
                - libxau6
                - libxcb1
                - libxdmcp6
                - libgl1-mesa-dri
                - libgl1-mesa-glx
                - libglu1-mesa
                - mesa-utils
